name: appppppp
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  #Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.1.0

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #Cached images
  cached_network_image: ^3.0.0

  #State Management
  get: ^4.6.5
  get_storage: ^2.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/background.png
    - assets/images/logodark.png
    - assets/images/logowhite.png
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/
    - assets/images/banner/
    - assets/images/product_veggies/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

